---
title: "Regression"
author: "Gretchen Ollani"
date: "2023-02-06"
output: html_document
---

---
title: "Regression"
author: "Gretchen D. Ollani"
date: "2023-01-10"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
theme_set(theme_bw())
```

```{r}
 #install datarium if not yet installed at the console
library(datarium) # loading datarium
```

```{r}
# Load the data
data("marketing", package = "datarium")
# Inspect the data
sample_n(marketing, 3)
```

```{r}
# Split the data into training and test set
set.seed(123)
training.samples <- marketing$sales %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- marketing[training.samples, ]
test.data <- marketing[-training.samples, ]
```

```{r}
# Build the model
model <- lm(sales ~., data = train.data)
# Summarize the model
summary(model)
# Make predictions
predictions <- model %>% predict(test.data)
# Model performance
# (a) Prediction error, RMSE
RMSE(predictions, test.data$sales)
# (b) R-square
R2(predictions, test.data$sales)
```

```{r}
# predicting with new data
# using the model
youtube <- 30
facebook <- 45
newspaper <- 12
a <- data.frame (youtube = 30,
                    facebook = 45,
                    newspaper = 13)
a <- data.frame(youtube, facebook, newspaper)
p <- model %>% predict(a)
p 
```

Our model is as follows:
$$\hat{y} = 3.59 + 0.04x_1 + 0.19x_2 +\epsilon$$